### ISSUE TITLE
Behind a reverse proxy https problem

### ISSUE THREAD

**Issue by ryno83** [nitsan-technologies/ns_sharethis#2]
Because we are behind a reverse proxy that handle the https thing, we get unsecure warning on our web site when using your plugin. The reverse proxy send the request to the backend web server in http mode then your plugin think that we are not over https (look at the line 55 of the ShareThisController.php). 

I suggest you to also look (not only at $_SERVER) at the TYPO3 conf vars [SYS][reverseProxySSL] to see if a reverse proxy handle the https. 

Thank you

[SYS][reverseProxySSL] =
String: '*' or list of IP addresses of proxies that use SSL (https) for the connection to the client, but an unencrypted connection (http) to the server. If '*' all proxies defined in [SYS][reverseProxyIP] use SSL.

**Comment by nitsan-technologies** [comment]
Thanks, Sébastien Verreault for MR https://github.com/nitsan-technologies/ns_sharethis/pull/3
